24 correcao
FGA-GCES/2020-2-SiGeD-Frontend pull request #3
Opened 2021-09-09 17:48 UTC by lucaslop

**Issue:** resolves [#24](https://github.com/DITGO/2020-2-SiGeD/issues/24)

## Descrição
Forma feitas duas atividades nessa issue. 

1 - Erros ao mostrar a lotação do usuário.

A lotação era um campo do tipo text. Depois da atualização, virou um campo acessível pelo array. Por isso, foi atualizado os campos para não ocasionar erros

2. - Mudança para dropdown
Antes era um input do tipo text. Agora, é um dropdown que recuperar os opções da API

2021-09-10 12:01 UTC, gustavolima00 requested changes

2021-09-10 12:01 UTC, gustavolima00 commented on src/Pages/ClientProfileScreen/index.js
> +        console.log(response.data);
Tira o console.log pra produção

2021-09-14 15:20 UTC, lucaslop commented on src/Pages/ClientProfileScreen/index.js
> +        console.log(response.data);
Resolvido

2021-09-14 15:21 UTC, gustavolima00 approved these changes

2021-09-15 15:01 UTC, merged